{
    'name': 'Stock Picking - Botones Orden de Venta y Facturas',
    'version': '18.0.3.6.4',
    'summary': 'Smart buttons, imágenes redimensionadas y mejoras visuales en traslados, facturas, ventas y productos',
    'author': 'AutomatePTY',
    'depends': ['stock', 'sale_stock', 'account', 'sale', 'product', 'purchase', 'mail', 'website_sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/shop_search_synonym_data.xml',
        'views/stock_picking_views.xml',
        'views/account_move_views.xml',
        'views/sale_order_views.xml',
        'views/sale_dianke_email_wizard_views.xml',
        'views/sale_confirm_payment_wizard_views.xml',
        'views/sale_order_dianke_export.xml',
        'views/product_views.xml',
        'views/purchase_order_views.xml',
        'views/report_invoice_inherit.xml',
        'views/report_deliveryslip_inherit.xml',
        'views/report_saleorder_inherit.xml',
        'views/product_kanban_search_inherit.xml',
        'views/purchase_bulk_email_wizard_views.xml',
        'views/res_partner_pricing_wizard_views.xml',
        'views/res_partner_pricing_action.xml',
        'views/shop_search_synonym_views.xml',
        'views/quick_order_templates.xml',
        'views/website_shop_templates.xml',
        'views/website_shop_page.xml',
        'views/website_shop_product_cart.xml',
        'views/website_home_blocks.xml',
        'views/website_home_hero.xml',
        'views/dkh_layout.xml',
        'views/dkh_banner_views.xml',
        'views/dkh_home.xml',
        'views/dkh_cart.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'stock_picking_sale_buttons/static/src/css/wrap_columns.css',
            'stock_picking_sale_buttons/static/src/js/picking_description.js',
        ],
        'web.assets_web': [
            'stock_picking_sale_buttons/static/src/css/wrap_columns.css',
        ],
        'web.assets_frontend': [
            'stock_picking_sale_buttons/static/src/css/shop_live_cart.css',
            'stock_picking_sale_buttons/static/src/css/shop_redesign.css',
            'stock_picking_sale_buttons/static/src/js/shop_live_cart.js',
            'stock_picking_sale_buttons/static/src/js/header_search.js',
            'stock_picking_sale_buttons/static/src/css/dkh.css',
            'stock_picking_sale_buttons/static/src/css/dkh_pages.css',
            'stock_picking_sale_buttons/static/src/js/dkh_shell.js',
            'stock_picking_sale_buttons/static/src/js/dkh_cart.js',
        ],
    },
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
