from . import stock_picking
from . import account_move
from . import sale_order
from . import sale_dianke_email_wizard
from . import sale_confirm_payment_wizard
from . import purchase_order
from . import purchase_bulk_email_wizard
from . import product_pricelist
from . import res_partner
from . import res_partner_pricing_wizard
from . import shop_search_synonym
from . import product_template_search
from . import website_search
from . import product_template_shop
from . import product_public_category
from . import website_dkh
from . import dkh_rules
from . import dkh_banner
